apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-owfl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-owfl
    app.kubernetes.io/part-of: partner-catalog-9
  name: partner-catalog-owfl
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-owfl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-owfl
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/asaran-tenant/partner-catalog-9/partner-catalog-owfl@sha256:b384bb1c1714e779fae942f9134d211a37c8fc3b3f853290f7a79270ea20d258
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
